<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Post extends Model
{
    protected $table = "posts";
    protected $fillable = ['name', 'slug', 'description', 'content', 'seo_title', 'seo_description', 'seo_keywords', 'category_id', 'views', 'rating_number', 'rating_value'];
    protected $with = ['categories', 'images'];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function images()
    {
        $images = Image::where('model_type', 'post')->where('model_id', $this->id)->get();
        foreach ($images as $image) {
            $image->delete();
        }
    }
    public static function boot()
    {
        // Trước khi xóa 1 post sẽ xóa các images, comments
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($post) {
            $post->deteteImages();
        });
    }
}
