<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    protected $table = "products";
    protected $fillable = ["name", "slug", "barcode", "description", "brand_id", "post_id", "model_type"];
//    protected $with =["posts", "categories", "brands", "images"];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class, 'brand_id', 'id');
    }
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class, 'post_id', 'id');
    }
    public function images()
    {
        $images = Image::where('model_type', 'post')->where('model_id', $this->id)->get();
        foreach ($images as $image) {
            $image->delete();
        }
    }


    public static function boot()
    {
        // Trước khi xóa 1 post sẽ xóa các images, comments
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($post) {
            $post->deteteImages();
        });
    }
}
